// Code generated by MockGen. DO NOT EDIT.
// Source: client.go
//
// Generated by this command:
//
//	mockgen -destination=./mocks/mock_github.go -package=mocks -source=client.go IGitHub
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	github "github.com/Afik17/GithubIssue/internal/github"
	gomock "go.uber.org/mock/gomock"
)

// MockIGitHub is a mock of IGitHub interface.
type MockIGitHub struct {
	ctrl     *gomock.Controller
	recorder *MockIGitHubMockRecorder
	isgomock struct{}
}

// MockIGitHubMockRecorder is the mock recorder for MockIGitHub.
type MockIGitHubMockRecorder struct {
	mock *MockIGitHub
}

// NewMockIGitHub creates a new mock instance.
func NewMockIGitHub(ctrl *gomock.Controller) *MockIGitHub {
	mock := &MockIGitHub{ctrl: ctrl}
	mock.recorder = &MockIGitHubMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIGitHub) EXPECT() *MockIGitHubMockRecorder {
	return m.recorder
}

// CloseIssue mocks base method.
func (m *MockIGitHub) CloseIssue(ctx context.Context, owner, repo string, number int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseIssue", ctx, owner, repo, number)
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseIssue indicates an expected call of CloseIssue.
func (mr *MockIGitHubMockRecorder) CloseIssue(ctx, owner, repo, number any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseIssue", reflect.TypeOf((*MockIGitHub)(nil).CloseIssue), ctx, owner, repo, number)
}

// CreateIssue mocks base method.
func (m *MockIGitHub) CreateIssue(ctx context.Context, owner, repo string, issueRequest *github.Issue) (*github.Issue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateIssue", ctx, owner, repo, issueRequest)
	ret0, _ := ret[0].(*github.Issue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateIssue indicates an expected call of CreateIssue.
func (mr *MockIGitHubMockRecorder) CreateIssue(ctx, owner, repo, issueRequest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateIssue", reflect.TypeOf((*MockIGitHub)(nil).CreateIssue), ctx, owner, repo, issueRequest)
}

// EditIssue mocks base method.
func (m *MockIGitHub) EditIssue(ctx context.Context, owner, repo string, number int, issue *github.Issue) (*github.Issue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EditIssue", ctx, owner, repo, number, issue)
	ret0, _ := ret[0].(*github.Issue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EditIssue indicates an expected call of EditIssue.
func (mr *MockIGitHubMockRecorder) EditIssue(ctx, owner, repo, number, issue any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EditIssue", reflect.TypeOf((*MockIGitHub)(nil).EditIssue), ctx, owner, repo, number, issue)
}

// GetIssueByNumber mocks base method.
func (m *MockIGitHub) GetIssueByNumber(ctx context.Context, owner, repo string, number int) (*github.Issue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIssueByNumber", ctx, owner, repo, number)
	ret0, _ := ret[0].(*github.Issue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIssueByNumber indicates an expected call of GetIssueByNumber.
func (mr *MockIGitHubMockRecorder) GetIssueByNumber(ctx, owner, repo, number any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIssueByNumber", reflect.TypeOf((*MockIGitHub)(nil).GetIssueByNumber), ctx, owner, repo, number)
}

// GetIssueByTitle mocks base method.
func (m *MockIGitHub) GetIssueByTitle(ctx context.Context, owner, repo, title, state string) (*github.Issue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIssueByTitle", ctx, owner, repo, title, state)
	ret0, _ := ret[0].(*github.Issue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIssueByTitle indicates an expected call of GetIssueByTitle.
func (mr *MockIGitHubMockRecorder) GetIssueByTitle(ctx, owner, repo, title, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIssueByTitle", reflect.TypeOf((*MockIGitHub)(nil).GetIssueByTitle), ctx, owner, repo, title, state)
}

// IssueHasLinkedPR mocks base method.
func (m *MockIGitHub) IssueHasLinkedPR(ctx context.Context, owner, repo string, number int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IssueHasLinkedPR", ctx, owner, repo, number)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IssueHasLinkedPR indicates an expected call of IssueHasLinkedPR.
func (mr *MockIGitHubMockRecorder) IssueHasLinkedPR(ctx, owner, repo, number any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IssueHasLinkedPR", reflect.TypeOf((*MockIGitHub)(nil).IssueHasLinkedPR), ctx, owner, repo, number)
}

// ListIssues mocks base method.
func (m *MockIGitHub) ListIssues(ctx context.Context, owner, repo, state string) ([]*github.Issue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListIssues", ctx, owner, repo, state)
	ret0, _ := ret[0].([]*github.Issue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListIssues indicates an expected call of ListIssues.
func (mr *MockIGitHubMockRecorder) ListIssues(ctx, owner, repo, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListIssues", reflect.TypeOf((*MockIGitHub)(nil).ListIssues), ctx, owner, repo, state)
}
